# Generated by Django 3.2.7 on 2023-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city360', '0003_wrkregg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('quantity', models.TextField()),
                ('user_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='order_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('disc', models.CharField(max_length=150)),
                ('file', models.FileField(max_length=150, upload_to='')),
                ('seller_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='sellerregg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('file', models.FileField(max_length=150, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='reportss',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='wrkregg',
        ),
        migrations.RemoveField(
            model_name='userregg',
            name='place',
        ),
    ]
