# Generated by Django 3.2.7 on 2023-07-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city360', '0005_auto_20230712_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('disc', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('seller_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='p_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
