# Generated by Django 3.2.7 on 2023-07-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city360', '0006_auto_20230713_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=100)),
                ('star', models.CharField(max_length=100)),
                ('u_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='returnitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=150)),
                ('return_reasons', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='wrkr_feedback',
            new_name='selr_feedback',
        ),
        migrations.RenameModel(
            old_name='user_feedback',
            new_name='user_feeback',
        ),
        migrations.RenameField(
            model_name='selr_feedback',
            old_name='uname',
            new_name='seller_id',
        ),
        migrations.RenameField(
            model_name='user_feeback',
            old_name='uname',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='auction',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
